export const USERNAME_POLICY = {
  minLength: 3,
  maxLength: 30,
  reserved: [
    "admin",
    "api",
    "app",
    "about",
    "account",
    "analytics",
    "auth",
    "blog",
    "careers",
    "dashboard",
    "destek",
    "developer",
    "docs",
    "edit",
    "explore",
    "favicon",
    "giris",
    "go",
    "help",
    "home",
    "iletisim",
    "legal",
    "login",
    "logout",
    "moderator",
    "new",
    "olnk",
    "onboarding",
    "pricing",
    "privacy",
    "profile",
    "register",
    "root",
    "search",
    "security",
    "settings",
    "signup",
    "signin",
    "signout",
    "static",
    "status",
    "support",
    "terms",
    "trpc",
    "user",
    "users",
    "verify",
    "www",
    "kayit",
    "ayarlar",
    "hakkimizda",
    "kosullar",
    "gizlilik",
  ],
  defaultBlockedTerms: [
    "orospu",
    "siktir",
    "sikik",
    "sikici",
    "yarrak",
    "amcik",
    "amcık",
    "gotveren",
    "götveren",
    "ibne",
    "kahpe",
    "porn",
    "porno",
    "pornhub",
    "onlyfans",
    "xnxx",
    "xvideos",
    "hentai",
    "nazi",
  ],
} as const;

export const USERNAME_UNAVAILABLE_MESSAGE = "Bu kullanıcı adı kullanılamıyor.";
