import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    AUTH_SECRET:
      process.env.NODE_ENV === "production"
        ? z.string().min(32)
        : z.string().optional(),
    AUTH_GOOGLE_ID: z.string().optional(),
    AUTH_GOOGLE_SECRET: z.string().optional(),
    EMAIL_SERVER: z.string().optional(),
    EMAIL_FROM: z.string().min(3).optional(),
    DATABASE_URL: z.string().url(),
    STRIPE_SECRET_KEY: z.string().startsWith("sk_").optional(),
    STRIPE_WEBHOOK_SECRET: z.string().startsWith("whsec_").optional(),
    IYZICO_API_KEY: z.string().optional(),
    IYZICO_SECRET_KEY: z.string().optional(),
    IYZICO_BASE_URL: z.string().url().default("https://api.iyzipay.com"),
    IYZICO_WEBHOOK_SECRET: z.string().optional(),
    IYZICO_MONTHLY_PLAN_CODE: z.string().optional(),
    IYZICO_YEARLY_PLAN_CODE: z.string().optional(),
    PAYTR_MERCHANT_ID: z.string().optional(),
    PAYTR_MERCHANT_KEY: z.string().optional(),
    PAYTR_MERCHANT_SALT: z.string().optional(),
    PAYTR_TEST_MODE: z.enum(["0", "1"]).default("0"),
    ADYEN_API_KEY: z.string().optional(),
    ADYEN_MERCHANT_ACCOUNT: z.string().optional(),
    ADYEN_HMAC_KEY: z.string().optional(),
    ADYEN_API_URL: z.string().url().default("https://checkout-test.adyen.com/v72"),
    ADYEN_RECURRING_URL: z.string().url().default("https://pal-test.adyen.com/pal/servlet/Recurring/v68"),
    LOCAL_PRO_MONTHLY_TRY: z.coerce.number().int().positive().optional(),
    LOCAL_PRO_YEARLY_TRY: z.coerce.number().int().positive().optional(),
    CRON_SECRET: z.string().min(24).optional(),
    STORAGE_ENDPOINT: z.string().url().optional(),
    STORAGE_REGION: z.string().optional(),
    STORAGE_BUCKET: z.string().optional(),
    STORAGE_ACCESS_KEY_ID: z.string().optional(),
    STORAGE_SECRET_ACCESS_KEY: z.string().optional(),
    STORAGE_PUBLIC_URL: z.string().url().optional(),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
    NEXT_PUBLIC_ADYEN_CLIENT_KEY: z.string().optional(),
    NEXT_PUBLIC_ADYEN_ENVIRONMENT: z.enum(["test", "live"]).default("test"),
  },
  runtimeEnv: {
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    EMAIL_SERVER: process.env.EMAIL_SERVER,
    EMAIL_FROM: process.env.EMAIL_FROM,
    DATABASE_URL: process.env.DATABASE_URL,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    IYZICO_API_KEY: process.env.IYZICO_API_KEY,
    IYZICO_SECRET_KEY: process.env.IYZICO_SECRET_KEY,
    IYZICO_BASE_URL: process.env.IYZICO_BASE_URL,
    IYZICO_WEBHOOK_SECRET: process.env.IYZICO_WEBHOOK_SECRET,
    IYZICO_MONTHLY_PLAN_CODE: process.env.IYZICO_MONTHLY_PLAN_CODE,
    IYZICO_YEARLY_PLAN_CODE: process.env.IYZICO_YEARLY_PLAN_CODE,
    PAYTR_MERCHANT_ID: process.env.PAYTR_MERCHANT_ID,
    PAYTR_MERCHANT_KEY: process.env.PAYTR_MERCHANT_KEY,
    PAYTR_MERCHANT_SALT: process.env.PAYTR_MERCHANT_SALT,
    PAYTR_TEST_MODE: process.env.PAYTR_TEST_MODE,
    ADYEN_API_KEY: process.env.ADYEN_API_KEY,
    ADYEN_MERCHANT_ACCOUNT: process.env.ADYEN_MERCHANT_ACCOUNT,
    ADYEN_HMAC_KEY: process.env.ADYEN_HMAC_KEY,
    ADYEN_API_URL: process.env.ADYEN_API_URL,
    ADYEN_RECURRING_URL: process.env.ADYEN_RECURRING_URL,
    LOCAL_PRO_MONTHLY_TRY: process.env.LOCAL_PRO_MONTHLY_TRY,
    LOCAL_PRO_YEARLY_TRY: process.env.LOCAL_PRO_YEARLY_TRY,
    CRON_SECRET: process.env.CRON_SECRET,
    STORAGE_ENDPOINT: process.env.STORAGE_ENDPOINT,
    STORAGE_REGION: process.env.STORAGE_REGION,
    STORAGE_BUCKET: process.env.STORAGE_BUCKET,
    STORAGE_ACCESS_KEY_ID: process.env.STORAGE_ACCESS_KEY_ID,
    STORAGE_SECRET_ACCESS_KEY: process.env.STORAGE_SECRET_ACCESS_KEY,
    STORAGE_PUBLIC_URL: process.env.STORAGE_PUBLIC_URL,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_ADYEN_CLIENT_KEY: process.env.NEXT_PUBLIC_ADYEN_CLIENT_KEY,
    NEXT_PUBLIC_ADYEN_ENVIRONMENT: process.env.NEXT_PUBLIC_ADYEN_ENVIRONMENT,
  },
  skipValidation: Boolean(process.env.SKIP_ENV_VALIDATION),
  emptyStringAsUndefined: true,
});
